# Generated by Django 4.1.5 on 2023-01-10 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_hospedes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('num_banheiros', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('pet_friendly', models.BooleanField(default=False)),
                ('valor_limpeza', models.DecimalField(decimal_places=2, max_digits=7)),
                ('data_ativacao', models.DateField()),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='imovel',
            constraint=models.CheckConstraint(check=models.Q(('data_ativacao__gte', models.F('dt_criacao'))), name='data_ativacao_depois_de_dt_criacao'),
        ),
    ]
