# Generated by Django 4.1.5 on 2023-01-11 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imovel',
            options={'verbose_name_plural': 'imoveis'},
        ),
    ]
