# Generated by Django 4.1.5 on 2023-01-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='taxa_plataforma',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
