# Generated by Django 4.1.5 on 2023-01-11 02:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncios', '0002_alter_anuncio_taxa_plataforma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('codigo', models.UUIDField(default=uuid.UUID('b3b37c6f-d54f-4d67-8a24-bde2de83ab6a'), editable=False, primary_key=True, serialize=False)),
                ('data_checkin', models.DateField()),
                ('data_checkout', models.DateField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('comentario', models.TextField(max_length=500)),
                ('num_hospedes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.anuncio')),
            ],
        ),
    ]
